// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-CJlBHgQB88ZSDUhroucOSkxz0x66KDA',
    appId: '1:458518962102:web:045b8696601a1a77726b17',
    messagingSenderId: '458518962102',
    projectId: 'auth-unit-test',
    authDomain: 'auth-unit-test.firebaseapp.com',
    storageBucket: 'auth-unit-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQpkfSqG-kZbY4yKZdUyJHHUf3kIkPs9Q',
    appId: '1:458518962102:android:3988631ef72c6ab5726b17',
    messagingSenderId: '458518962102',
    projectId: 'auth-unit-test',
    storageBucket: 'auth-unit-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEKKAvMxeyNShXlS9NaBRsAfIhAIe4jM',
    appId: '1:458518962102:ios:b0e2ababc37f74ae726b17',
    messagingSenderId: '458518962102',
    projectId: 'auth-unit-test',
    storageBucket: 'auth-unit-test.appspot.com',
    iosClientId: '458518962102-orgt92oeu80o0tc5ete6a2e4uracg3oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhEKKAvMxeyNShXlS9NaBRsAfIhAIe4jM',
    appId: '1:458518962102:ios:cffb1d87ce07f588726b17',
    messagingSenderId: '458518962102',
    projectId: 'auth-unit-test',
    storageBucket: 'auth-unit-test.appspot.com',
    iosClientId: '458518962102-9td61jsfgcmls8rku7k3uk063er5vji5.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest.RunnerTests',
  );
}
